// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxeqS3oKQlu7gtnuRzcDaA9lH43m5qYwE',
    appId: '1:5129010252:web:5d598e7f594e500ec808e9',
    messagingSenderId: '5129010252',
    projectId: 'smart-spend-ab121',
    authDomain: 'smart-spend-ab121.firebaseapp.com',
    storageBucket: 'smart-spend-ab121.firebasestorage.app',
    measurementId: 'G-YZJ0VWRWFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmT188FZbFP-UOKYbSV1A7tX9tePC0SbA',
    appId: '1:5129010252:android:608b3fc2aeae49b5c808e9',
    messagingSenderId: '5129010252',
    projectId: 'smart-spend-ab121',
    storageBucket: 'smart-spend-ab121.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByLdwrJl2_VKKslE_78krYAHPcBLowkLk',
    appId: '1:5129010252:ios:2f50bc459db9d377c808e9',
    messagingSenderId: '5129010252',
    projectId: 'smart-spend-ab121',
    storageBucket: 'smart-spend-ab121.firebasestorage.app',
    iosBundleId: 'com.example.smartExpens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxeqS3oKQlu7gtnuRzcDaA9lH43m5qYwE',
    appId: '1:5129010252:web:c2a2704def4d996fc808e9',
    messagingSenderId: '5129010252',
    projectId: 'smart-spend-ab121',
    authDomain: 'smart-spend-ab121.firebaseapp.com',
    storageBucket: 'smart-spend-ab121.firebasestorage.app',
    measurementId: 'G-6L98JH47HJ',
  );
}
